events {}

http {
    map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
    }

     # Upstream cho frontend
    upstream frontend {
        server frontend:80; # Port 80 trong container Frontend
    }

    # Upstream cho backend-website
    upstream backend-website {
        server backend-website:5000; # Port 5000 trong container backend-website
    }

    # Upstream cho backend-chat
    upstream backend-chat {
        server backend-chat:4000; # Port 4000 trong container backend-chat
    }

    server {
        listen 80;

         # Proxy pass cho frontend
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Configuration for web
        location /http {
            rewrite ^/http/(.*)$ /$1 break;
            proxy_pass http://backend-website;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # Configuration for api
        location /socket.io/ {
            proxy_pass http://backend-chat; # Đảm bảo upstream đúng
            proxy_redirect off;
            proxy_http_version      1.1;
            proxy_set_header        Upgrade                 $http_upgrade;
            proxy_set_header        Connection              "upgrade";
            proxy_set_header        Host                    $host;
            proxy_set_header        X-Real-IP               $remote_addr;
            proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
           
        }
    }
}
